// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScraperMF.Data;

namespace WebScraperMF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210116140929_addCurrencyToDB")]
    partial class addCurrencyToDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebScraperMF.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("productImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("productPrice")
                        .HasColumnType("float");

                    b.Property<string>("productPriceCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("productSearchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("productTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productWebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
